import { useState, useEffect, useRef } from "react";

interface options {
  root: null;
  rootMargin: string;
  threshold: number;
}

export interface VisibleStates {
  [key: string]: boolean;
  "welcome-message": boolean;
  "welcome-box": boolean;
  "generate-section": boolean;
  "quiz-cards-container": boolean;
  "quiz-cards": boolean;
}

export interface Refs {
  current: HTMLElement[];
}

export const useElementOnScreen = (options: options) => {
  const { root, rootMargin, threshold } = options;

  //   const refs = useRef<Refs>({ current: [] });
  const refs = useRef<HTMLElement[]>([]);

  const [visibleStates, setVisibleStates] = useState<VisibleStates>({
    "welcome-message": false,
    "welcome-box": false,
    "generate-section": false,
    "quiz-cards-container": false,
    "quiz-cards": false,
  });

  const callbackFunction = (entries: IntersectionObserverEntry[]) => {
    entries.forEach((entry) => {
      setVisibleStates((prevVisibleStates) => ({
        ...prevVisibleStates,
        [entry.target.id]: entry.isIntersecting,
      }));
    });
  };

  useEffect(() => {
    const currentRefs = Array.from(refs.current);
    const observer = new IntersectionObserver(callbackFunction, {
      root: root,
      rootMargin: rootMargin,
      threshold: threshold,
    });
    currentRefs.forEach((ref) => {
      if (ref) observer.observe(ref);
    });
    return () => {
      currentRefs.forEach((ref) => {
        if (ref) observer.unobserve(ref);
      });
    };
  }, [refs, root, rootMargin, threshold]);
  return { refs, visibleStates };
};

export const preparedQuizzes = [
  {
    category: "History",
    description:
      "A thrilling journey through time with historical events and legendary figures",
    image: "/images/history-card.webp",
    smallerImage: "/images/history-card-sm.webp",
    questions: [
      {
        category: "history",
        id: "622a1c3c7cc59eab6f951a70",
        correctAnswer: "Mother Teresa",
        incorrectAnswers: [
          "Florence Nightingale",
          "Marie Curie",
          "Margaret Thatcher",
        ],
        question: {
          text: "Who won the 1979 Nobel Peace Prize for her work among the poor?",
        },
        tags: ["history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "62611f7e4b176d54800e3d5d",
        correctAnswer: "1961",
        incorrectAnswers: ["1947", "1954", "1968"],
        question: {
          text: "In which year was the first human sent into space?",
        },
        tags: [
          "events",
          "firsts",
          "space_exploration",
          "exploration",
          "cold_war",
          "history",
        ],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c367cc59eab6f95034a",
        correctAnswer: "Franklin Roosevelt",
        incorrectAnswers: [
          "Dwight Eisenhower",
          "Lyndon B. Johnson",
          "Harry Truman",
        ],
        question: {
          text: "Who Was President Of The USA At The Outbreak Of World War II?",
        },
        tags: ["history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c3c7cc59eab6f951a24",
        correctAnswer: "Et tu, Brute?",
        incorrectAnswers: ["Veni, Vidi, Vici.", "Carpe Diem!", "Memento Mori?"],
        question: {
          text: "What are commonly believed to be the last words of Julius Caesar?",
        },
        tags: ["history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c3c7cc59eab6f951b3a",
        correctAnswer: "China",
        incorrectAnswers: ["Spain", "Brazil", "Australia"],
        question: {
          text: "In which country did the Boxer Rebellion take place?",
        },
        tags: ["history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c3c7cc59eab6f95197e",
        correctAnswer: "Dunkirk",
        incorrectAnswers: ["Calais", "La Havre", "Dieppe"],
        question: {
          text: "From which French port did 200,000 British troops flee in 1940?",
        },
        tags: ["world_war_2", "wars", "france", "uk", "1940's", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c377cc59eab6f950441",
        correctAnswer: "John Lennon ",
        incorrectAnswers: ["Malcolm X", "John F Kennedy", "Martin Luther King"],
        question: {
          text: "Who was assassinated on Dec. 8, 1980 in New York City? ",
        },
        tags: ["history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "64824ee47778562fd76a96a4",
        correctAnswer: "Squire",
        incorrectAnswers: ["Tourney", "Knight errant", "Groom"],
        question: {
          text: "What was the name given to a knight's student?",
        },
        tags: ["words", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c3c7cc59eab6f9517c7",
        correctAnswer: "Captain Vancouver",
        incorrectAnswers: [
          "Captain Alaska",
          "Captain Washington",
          "Captain Canada",
        ],
        question: {
          text: "Which explorer is best known for exploring and surveying  North America's northwest Pacific coast regions?",
        },
        tags: ["history", "people", "exploration"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c3c7cc59eab6f951a6b",
        correctAnswer: "Singapore",
        incorrectAnswers: ["Taiwan", "Thailand", "Myanmar"],
        question: {
          text: "Sir Stamford Raffles founded which Asian nation?",
        },
        tags: ["history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
    ],
  },
  {
    category: "Music",
    description: "Rock out with trivia about music and musicians",
    image: "/images/music-card.webp",
    smallerImage: "/images/music-card-sm.webp",
    questions: [
      {
        category: "music",
        id: "622a1c3b7cc59eab6f951745",
        correctAnswer: "Chris Rea",
        incorrectAnswers: ["Brian Jelico", "Kevin Dober", "David Duschamps"],
        question: {
          text: "Which singer released Driving Home for Christmas in 1988?",
        },
        tags: ["songs", "music", "christmas", "1980's"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "music",
        id: "622a1c397cc59eab6f950d69",
        correctAnswer: "Genesis",
        incorrectAnswers: [
          "Orchestral Manoeuvres in the Dark",
          "Soft Machine",
          "The Human League",
        ],
        question: {
          text: "Which band includes 'Phil Collins'?",
        },
        tags: ["music"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "music",
        id: "622a1c347cc59eab6f94fb97",
        correctAnswer: "\"Don't Stop Believin'\" by Journey",
        incorrectAnswers: [
          '"Welcome to the Black Parade" by My Chemical Romance',
          '"All Along the Watchtower" by Bob Dylan',
          '"All I Want For Christmas Is You" by Mariah Carey',
        ],
        question: {
          text: 'Which song begins with the lyrics: "Just a small town girl, living in a lonely world."?',
        },
        tags: ["songs", "lyrics", "music"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "music",
        id: "622a1c397cc59eab6f950d40",
        correctAnswer: "Green Day",
        incorrectAnswers: ["Mastodon", "Fall Out Boy", "Blink-182"],
        question: {
          text: "'Dookie' is a classic 90's punk rock album by which band?",
        },
        tags: ["1990's", "music"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "music",
        id: "622a1c357cc59eab6f94ff40",
        correctAnswer: "Michael Jackson",
        incorrectAnswers: ["Nicki Minaj", "Neil Young", "Eric Clapton"],
        question: {
          text: "Which American singer, songwriter and dancer released the song 'Love Never Felt So Good'?",
        },
        tags: ["songs", "music"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "music",
        id: "622a1c397cc59eab6f950dc3",
        correctAnswer: "Green Day",
        incorrectAnswers: ["Mastodon", "Animal Collective", "Fall Out Boy"],
        question: {
          text: "Which band includes 'Billie Joe Armstrong'?",
        },
        tags: ["music"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "music",
        id: "645ba87ff09106226db23586",
        correctAnswer: "Gloria",
        incorrectAnswers: ["Lucy", "Sally", "Mary"],
        question: {
          text: "Which popular name for girls was sung about by Van Morrison, The Doors, U2, and Laura Branigan?",
        },
        tags: ["music", "names", "songs"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "music",
        id: "64824e287778562fd76a960e",
        correctAnswer: "Adele",
        incorrectAnswers: ["Taylor Swift", "Ed Sheeran", "Beyoncé"],
        question: {
          text: 'Released in 2008, which artist\'s debut album was titled "19"?',
        },
        tags: ["music", "music_albums"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "music",
        id: "645c9f8f42ea81e2554c5f57",
        correctAnswer: "I Will Always Love You",
        incorrectAnswers: [
          "My Heart Will Go On",
          "Everything I Do (I Do It For You)",
          "Uptown Funk",
        ],
        question: {
          text: "Which song did Whitney Houston have a 1992 hit with?",
        },
        tags: ["music", "songs"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "music",
        id: "622a1c357cc59eab6f94feeb",
        correctAnswer: "David Bowie",
        incorrectAnswers: ["Eric Clapton", "Paul McCartney", "George Michael"],
        question: {
          text: "Which British musician collaborated with Queen on the song 'Under Pressure'?",
        },
        tags: ["songs", "musicians", "general_knowledge", "music"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
    ],
  },
  {
    category: "Film and TV",
    description:
      "Challenge your inner movie buff with a quiz about films and TV shows",
    image: "/images/film-and-tv-card.webp",
    smallerImage: "/images/film-and-tv-card-sm.webp",
    questions: [
      {
        category: "film_and_tv",
        id: "62573f593d2f5c16bfb88330",
        correctAnswer:
          "A secretary checks into a remote motel run by a young man under the domination of his mother.",
        incorrectAnswers: [
          "The story of how the scandal of child molestation within the Boston Catholic church was uncovered.",
          "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler.",
          "When a heist goes wrong, the surviving criminals suspect that one of them is a police informant.",
        ],
        question: {
          text: "What is the plot of the movie Psycho?",
        },
        tags: ["film", "film_and_tv"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "film_and_tv",
        id: "647c9855f89e0968cfbc1a29",
        correctAnswer: "Homeland",
        incorrectAnswers: ["Badland", "Madland", "Motherland"],
        question: {
          text: "What is the name of the TV drama starring Claire Danes that was popular throughout the 2010s?",
        },
        tags: ["tv", "film_and_tv"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "film_and_tv",
        id: "625740579da29df7b05f73d6",
        correctAnswer: "The Elephant Man",
        incorrectAnswers: [
          "Vertigo",
          "Back to the Future",
          "Mr. Smith Goes to Washington",
        ],
        question: {
          text: "Name the movie that matches the following plot summary: 'A surgeon rescues a disfigured man who is mistreated while scraping a living as a side-show freak.'",
        },
        tags: ["film", "film_and_tv"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "film_and_tv",
        id: "6257409d9da29df7b05f73eb",
        correctAnswer: "Million Dollar Baby",
        incorrectAnswers: ["Lawrence of Arabia", "Vertigo", "Monsters, Inc."],
        question: {
          text: "Name the movie that matches the following plot summary: 'A woman works with a hardened boxing trainer to become a professional.'",
        },
        tags: ["film", "film_and_tv"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "film_and_tv",
        id: "622a1c3d7cc59eab6f951c96",
        correctAnswer: "Michael Caine",
        incorrectAnswers: [
          "Patrick Stewart",
          "Christopher Lee",
          "Daniel Day Lewis",
        ],
        question: {
          text: 'Which Oscar Winning Actor Played Scrooge In "The Muppet Christmas Carol"?',
        },
        tags: ["film_and_tv"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "film_and_tv",
        id: "63d95301168979b94b2e4f75",
        correctAnswer: "The Fresh Prince of Bel-Air",
        incorrectAnswers: ["Seinfeld", "Friends", "Home Improvement"],
        question: {
          text: "What was the name of the popular '90s sitcom starring Will Smith?",
        },
        tags: ["1990's", "film_and_tv", "tv"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "film_and_tv",
        id: "622a1c3c7cc59eab6f9518bd",
        correctAnswer: "Vera",
        incorrectAnswers: ["Shea", "Daphne", "Mary"],
        question: {
          text: "What was the name of Norm's wife on Cheers?",
        },
        tags: ["tv", "fictitious_characters", "film_and_tv"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "film_and_tv",
        id: "62573f119da29df7b05f7386",
        correctAnswer: "One Flew Over the Cuckoo's Nest",
        incorrectAnswers: [
          "The Father",
          "The Deer Hunter",
          "The Treasure of the Sierra Madre",
        ],
        question: {
          text: "Name the movie that matches the following plot summary: 'A criminal pleads insanity and is admitted to a mental institution.'",
        },
        tags: ["film", "film_and_tv"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "film_and_tv",
        id: "646339a001d576cfac3aa396",
        correctAnswer: "Cheers & Frasier",
        incorrectAnswers: [
          "Seinfeld & Friends",
          "The Big Bang Theory & How I Met Your Mother",
          "The Office & Brooklyn Nine-Nine",
        ],
        question: {
          text: "On which two popular sitcoms has Bebe Neuwirth played Dr. Lilith Sternin?",
        },
        tags: ["sitcoms", "tv", "film_and_tv", "acting"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "film_and_tv",
        id: "625740179da29df7b05f73c3",
        correctAnswer: "L.A. Confidential",
        incorrectAnswers: ["Aliens", "Schindler's List", "Raging Bull"],
        question: {
          text: "Name the movie that matches the following plot summary: 'Three policemen investigate a series of murders with their own brand of justice.'",
        },
        tags: ["film", "film_and_tv"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
    ],
  },
  {
    category: "Arts and Literature",
    description: "Immerse yourself in the world of arts and literature",
    image: "/images/arts-and-literature-card.webp",
    smallerImage: "/images/arts-and-literature-card-sm.webp",
    questions: [
      {
        category: "arts_and_literature",
        id: "622a1c397cc59eab6f950f27",
        correctAnswer: "Leo Tolstoy",
        incorrectAnswers: [
          "Ivan Turgenev",
          "Henryk Sienkiewicz",
          "Alphonse Daudet",
        ],
        question: {
          text: "Which author wrote 'War and Peace'?",
        },
        tags: ["arts_and_literature"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "arts_and_literature",
        id: "622a1c347cc59eab6f94f95e",
        correctAnswer: "To Kill A Mockingbird",
        incorrectAnswers: [
          "The Big Sleep",
          "The Wind in the Willows",
          "The Sun Also Rises",
        ],
        question: {
          text: "Which book contains the character 'Arthur 'Boo' Radley'?",
        },
        tags: [
          "fictitious_characters",
          "classic_novels",
          "literature",
          "arts_and_literature",
        ],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "arts_and_literature",
        id: "622a1c3a7cc59eab6f951362",
        correctAnswer: "Neoclassicism",
        incorrectAnswers: ["Romanticism", "Fauvism", "Impressionism"],
        question: {
          text: "Which artistic style of the late eighteenth and early nineteenth centuries revived the order and harmony of ancient Greek and Roman art?",
        },
        tags: ["words", "art", "arts_and_literature"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "arts_and_literature",
        id: "622a1c3b7cc59eab6f9513c1",
        correctAnswer: "Little Women",
        incorrectAnswers: ["Buddenbrooks", "David Copperfield", "Jane Eyre"],
        question: {
          text: "In which book does 'Meg March' appear?",
        },
        tags: ["arts_and_literature"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "arts_and_literature",
        id: "622a1c397cc59eab6f950f55",
        correctAnswer: "Isaac Asimov",
        incorrectAnswers: [
          "Ursula K. Le Guin",
          "Philip K. Dick",
          "Stephen King",
        ],
        question: {
          text: "Which author wrote 'Foundation’s Edge'?",
        },
        tags: ["arts_and_literature"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "arts_and_literature",
        id: "622a1c397cc59eab6f950f80",
        correctAnswer: "Stephen King",
        incorrectAnswers: ["H. P. Lovecraft", "Edgar Allan Poe", "Jack Vance"],
        question: {
          text: "Which author wrote 'It'?",
        },
        tags: ["arts_and_literature"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "arts_and_literature",
        id: "622a1c397cc59eab6f950e71",
        correctAnswer: "Albert Camus",
        incorrectAnswers: [
          "François-René de Chateaubriand",
          "Anatole France",
          "Guy de Maupassant",
        ],
        question: {
          text: "Which author wrote 'The Stranger'?",
        },
        tags: ["arts_and_literature"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "arts_and_literature",
        id: "622a1c397cc59eab6f950ee7",
        correctAnswer: "H. G. Wells",
        incorrectAnswers: ["Neil Gaiman", "Arthur C. Clarke", "C. S. Lewis"],
        question: {
          text: "Which author wrote 'The War of the Worlds'?",
        },
        tags: [],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "arts_and_literature",
        id: "622a1c3a7cc59eab6f951330",
        correctAnswer: "James Joyce",
        incorrectAnswers: ["Oscar Wilde", "Kurt Vonnegut", "Charles Dickens"],
        question: {
          text: "Which author  wrote Ulysses, Giacomo Joyce, Dubliners and Finnegans Wake?",
        },
        tags: ["arts_and_literature", "literature", "classic_novels", "people"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "arts_and_literature",
        id: "622a1c367cc59eab6f9501b4",
        correctAnswer: "Gone with the Wind",
        incorrectAnswers: [
          "The Fall of the King",
          "All Quiet on the Western Front",
          "A Tale of Two Cities",
        ],
        question: {
          text: "Which piece of written work starts with the line 'Scarlett O’Hara was not beautiful, but men seldom realized it when caught by her charm as the Tarleton twins were.'?",
        },
        tags: ["literature", "quotes", "arts_and_literature"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
    ],
  },
  {
    category: "Society and Culture",
    description: "Dive into the rich tapestry of society and culture",
    image: "/images/society-and-culture-card.webp",
    smallerImage: "/images/society-and-culture-card-sm.webp",
    questions: [
      {
        category: "society_and_culture",
        id: "622a1c367cc59eab6f95012b",
        correctAnswer: "Janus",
        incorrectAnswers: ["Mars", "Octavian", "Septimus"],
        question: {
          text: "Which Roman god of doorways and passages is the two headed deity from which we get the name of one of our months?",
        },
        tags: ["mythology", "romans", "classics", "society_and_culture"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "society_and_culture",
        id: "62ab33175202de619af2813d",
        correctAnswer: "Bugatti",
        incorrectAnswers: ["Honda", "Ferrari", "Chevrolet"],
        question: {
          text: "Which car manufacturer makes the Veyron?",
        },
        tags: ["motoring", "business", "society_and_culture"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "society_and_culture",
        id: "6463395501d576cfac3aa354",
        correctAnswer: "Thar she blows!",
        incorrectAnswers: [
          "Land Ahoy!",
          "Dive! Dive! Dive!",
          "Look alive, boys!",
        ],
        question: {
          text: "What is the traditional cry heard when a whaling boat spots a whale?",
        },
        tags: ["sailing", "society_and_culture", "phrases"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "society_and_culture",
        id: "6266e64aff2394bd44dee03f",
        correctAnswer: "Four",
        incorrectAnswers: ["One", "Five", "Three"],
        question: {
          text: "In German, what is the meaning of the word 'vier'?",
        },
        tags: ["language", "translations", "society_and_culture"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "society_and_culture",
        id: "64824f247778562fd76a96d2",
        correctAnswer: "L. Ron Hubbard",
        incorrectAnswers: ["J.R.R. Tolkien", "Joseph Smith", "P. T. Barnum"],
        question: {
          text: "Who was the founder of Scientology?",
        },
        tags: ["religion", "people", "society_and_culture"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "society_and_culture",
        id: "6266e63cff2394bd44dee03b",
        correctAnswer: "Three",
        incorrectAnswers: ["Two", "Yellow", "Ten"],
        question: {
          text: "In Spanish, what is the meaning of the word 'tres'?",
        },
        tags: ["language", "translations", "society_and_culture"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "society_and_culture",
        id: "62c2fa15b3eadb0437fda6c2",
        correctAnswer: "Swarovski",
        incorrectAnswers: ["Mustang", "Ferrari", "Bacardi"],
        question: {
          text: "Which of these brands has a swan on its logo?",
        },
        tags: [
          "society_and_culture",
          "business",
          "marketing",
          "animals",
          "birds",
        ],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "society_and_culture",
        id: "6463395701d576cfac3aa35c",
        correctAnswer: "The Hippocratic Oath",
        incorrectAnswers: [
          "The Nightingale's Pledge",
          "The Socratic Oath",
          "The Ecclesiast Pledge",
        ],
        question: {
          text: "What is the name of the oath traditionally taken by doctors, which originated in ancient Greece and is still associated with the medical profession today?",
        },
        tags: ["philosophy", "society_and_culture", "healthcare", "medicine"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "society_and_culture",
        id: "6462628bab138b829b81ea27",
        correctAnswer: "May Day",
        incorrectAnswers: [
          "St. Patrick's Day",
          "Easter Sunday",
          "Christmas Day",
        ],
        question: {
          text: "What is the name of the celebration to mark the beginning of summer, which sometimes includes dancing around a pole and giving baskets of flowers to friends and family?",
        },
        tags: ["traditions", "celebrations", "society_and_culture"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "society_and_culture",
        id: "622a1c367cc59eab6f950115",
        correctAnswer: "Jerusalem",
        incorrectAnswers: ["Baghdad", "Tel Aviv", "Bethlehem"],
        question: {
          text: "Which city is sacred to Jews, Christians, and Muslims?",
        },
        tags: [
          "cities",
          "religion",
          "christianity",
          "islam",
          "judaism",
          "general_knowledge",
          "society_and_culture",
        ],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
    ],
  },
  {
    category: "Science",
    description:
      "Unleash your inner scientist with mind-blowing facts and discoveries",
    image: "/images/science-card.webp",
    smallerImage: "/images/science-card-sm.webp",
    questions: [
      {
        category: "science",
        id: "622a1c3a7cc59eab6f950fda",
        correctAnswer: "Coca Cola",
        incorrectAnswers: ["Dr Pepper", "Lucozade", "Irn Bru"],
        question: {
          text: "Which Significant Did Dr John Pemberton Of Atlanta Georgia Invent In 1886?",
        },
        tags: ["science"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "science",
        id: "622a1c397cc59eab6f950fba",
        correctAnswer: "Charles Babbage",
        incorrectAnswers: ["Ada Lovelace", "Leonard Adleman", "John Atanasoff"],
        question: {
          text: "Who Is Considered As The Originator Of The Concept Of A Computer?",
        },
        tags: ["science"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "science",
        id: "622a1c397cc59eab6f950faa",
        correctAnswer: "Archimedes",
        incorrectAnswers: ["Pythagoras", "Euclid", "Aristotle"],
        question: {
          text: "Who Famously Shouted 'Eureka!'?",
        },
        tags: ["people", "words", "quotes", "philosophy", "science"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "science",
        id: "622a1c377cc59eab6f9504cb",
        correctAnswer: "prehistoric climates",
        incorrectAnswers: [
          "cancer",
          "the study and science of phenomena as distinct from the science of actual existence or being",
          "a branch of soil science that studies the influence of soil on life",
        ],
        question: {
          text: "What is Paleoclimatology the study of?",
        },
        tags: ["science"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "science",
        id: "622a1c377cc59eab6f9504a4",
        correctAnswer:
          "the specialty in medicine that deals with diseases of the lungs and the respiratory tract",
        incorrectAnswers: [
          "fossil footprints, tracks and burrows",
          "classification",
          "the mathematical study of closeness and connectedness",
        ],
        question: {
          text: "What is Pulmonology the study of?",
        },
        tags: ["science"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "science",
        id: "62433431cfaae40c1296142a",
        correctAnswer: "A Boar",
        incorrectAnswers: ["A Drake", "A Tom", "A Ram"],
        question: {
          text: "What is a male guinea pig known as?",
        },
        tags: ["science"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "science",
        id: "624335becfaae40c129614c7",
        correctAnswer: "A Stallion",
        incorrectAnswers: ["A Buck", "A Dog", "A Ram"],
        question: {
          text: "What is the word for a male zebra?",
        },
        tags: ["words", "animals", "science"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "science",
        id: "622a1c3a7cc59eab6f951091",
        correctAnswer: "Centipedes And Millipedes",
        incorrectAnswers: [
          "Crabs and Lobsters",
          "Slugs and Snails",
          "Scorpions and Spiders",
        ],
        question: {
          text: "Which of these pairs are Myriapods?",
        },
        tags: ["science"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "science",
        id: "63d9531d168979b94b2e4f9d",
        correctAnswer: "Jonas Salk",
        incorrectAnswers: [
          "Edward Jenner",
          "Alexander Fleming",
          "Louis Pasteur",
        ],
        question: {
          text: "Who developed the polio vaccine?",
        },
        tags: ["science", "medicine", "scientific_discoveries", "people"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "science",
        id: "645c9f8f42ea81e2554c5f4d",
        correctAnswer: "regression",
        incorrectAnswers: ["repression", "dissociation", "projection"],
        question: {
          text: "Which term in psychology refers to the process of reverting to an earlier, childlike form of behavior?",
        },
        tags: ["psychology", "science", "words"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
    ],
  },
  {
    category: "Geography",
    description: "Embark on an adventure with geographical trivia",
    image: "/images/geography-card.webp",
    smallerImage: "/images/geography-card-sm.webp",
    questions: [
      {
        category: "geography",
        id: "625e9f6a796f721e95543f9b",
        correctAnswer: "Red",
        incorrectAnswers: ["Orange", "Gold", "Yellow"],
        question: {
          text: "Which of these colors is included on the flag of Netherlands?",
        },
        tags: ["flags", "geography"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "geography",
        id: "62602ff44b176d54800e3d06",
        correctAnswer: "Georgia",
        incorrectAnswers: ["Pakistan", "Tajikistan", "Azerbaijan"],
        question: {
          text: "Tbilisi is a city in which country?",
        },
        tags: ["cities", "geography"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "geography",
        id: "646262f6ab138b829b81ea72",
        correctAnswer: "Chile",
        incorrectAnswers: ["Argentina", "Mexico", "Brazil"],
        question: {
          text: "Which of these countries is between Bolivia and the Pacific Ocean?",
        },
        tags: ["countries", "south_america", "geography"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "geography",
        id: "623388fc0161109f922aacbd",
        correctAnswer: "Gibraltar ",
        incorrectAnswers: ["Valencia", "Maroc", "Moor"],
        question: {
          text: "Which Rock Is On The South Coast Of Spain?",
        },
        tags: ["geography"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "geography",
        id: "625e9e8f27d267462ff91757",
        correctAnswer: "Germany",
        incorrectAnswers: ["Georgia", "Peru", "Malaysia"],
        question: {
          text: "Which country's flag can be described as 'Three equal horizontal bands of black red and gold.'?",
        },
        tags: ["flags", "geography"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "geography",
        id: "62602d444b176d54800e3c8b",
        correctAnswer: "Osaka",
        incorrectAnswers: ["Adelaide", "Incheon", "Gold Coast"],
        question: {
          text: "Which of these cities is in Japan?",
        },
        tags: ["cities", "asia", "japan", "geography"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "geography",
        id: "623375c162eaad73716a86c5",
        correctAnswer: "Nova Scotia",
        incorrectAnswers: ["Quebec", "Labrador", "Alberta"],
        question: {
          text: "Halifax is the capital of which Canadian province?",
        },
        tags: ["canada", "geography"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "geography",
        id: "622a1c387cc59eab6f950ac0",
        correctAnswer: "San Marino",
        incorrectAnswers: ["Croatia", "Monaco", "Liechtenstein"],
        question: {
          text: "Which of these countries borders Italy?",
        },
        tags: ["geography"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "geography",
        id: "6463398b01d576cfac3aa37d",
        correctAnswer: "Tricolor",
        incorrectAnswers: [
          "Red, White, and Blue",
          "The Golden Fleece",
          "The Union Jack",
        ],
        question: {
          text: "What is the name of the French flag?",
        },
        tags: ["flags", "france", "geography"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "geography",
        id: "64a1c901c1e45722061c31b5",
        correctAnswer: "Gulf of St. Lawrence",
        incorrectAnswers: ["Hudson Bay", "Bay of Fundy", "Gulf of Mexico"],
        question: {
          text: "Which body of water is located between Newfoundland and the Canadian mainland?",
        },
        tags: ["geography", "canada", "bodies_of_water"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
    ],
  },
  {
    category: "Food and Drink",
    description: "Feast your mind on delicious food and beverage trivia",
    image: "/images/food-and-drink-card.webp",
    smallerImage: "/images/food-and-drink-card-sm.webp",
    questions: [
      {
        category: "food_and_drink",
        id: "647f9da93a4302a7192715f1",
        correctAnswer: "A bagel",
        incorrectAnswers: ["A croissant", "A muffin", "A doughnut"],
        question: {
          text: "What breakfast item takes its name from the Yiddish word for 'ring' or 'bracelet'?",
        },
        tags: ["breakfast", "food", "food_and_drink"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "food_and_drink",
        id: "622a1c367cc59eab6f9502b8",
        correctAnswer: "Egg Nog ",
        incorrectAnswers: ["Milkshake", "Cappuccino", "Lassi"],
        question: {
          text: "What Milky Drink Is Often Drank On New Years Eve?",
        },
        tags: ["drink", "food_and_drink"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "food_and_drink",
        id: "622a1c367cc59eab6f9502a2",
        correctAnswer: "Tubular ",
        incorrectAnswers: ["Anulus", "Spiral", "Shell"],
        question: {
          text: "What shape is macaroni?",
        },
        tags: ["food", "food_and_drink"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "food_and_drink",
        id: "645fcc89541c4d4fc8cf3088",
        correctAnswer: "Eggplant",
        incorrectAnswers: ["Cucumber", "Avocado", "Cauliflower"],
        question: {
          text: "What vegetable is traditionally used in moussaka, a Greek baked dish made with ground lamb or beef?",
        },
        tags: ["food", "food_and_drink", "vegetables"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "food_and_drink",
        id: "622a1c367cc59eab6f95028b",
        correctAnswer: "Self-Raising Flour ",
        incorrectAnswers: [
          "Artificial Sweetener",
          "Decaffeinated Coffee",
          "Taurine",
        ],
        question: {
          text: "What was discovered by the McDougall Brothers in 1864 after an experiment with phosphatic yeast?",
        },
        tags: ["food_and_drink"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "food_and_drink",
        id: "625006f10d86c8f685d80f08",
        correctAnswer: "Stuffed pasta",
        incorrectAnswers: ["Soup pasta", "Strand pasta", "Ribbon pasta"],
        question: {
          text: "What type of pasta is ravioli?",
        },
        tags: ["food", "italy", "food_and_drink"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "food_and_drink",
        id: "64e6fd9b0b79e5bedd55c8bf",
        correctAnswer: "Crudites",
        incorrectAnswers: ["Amouse Bouche", "Béchamel", "Poisson"],
        question: {
          text: "In French cooking, what is the word for an appetizer of raw vegetables?",
        },
        tags: ["cuisine", "france", "food", "food_and_drink"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "food_and_drink",
        id: "622a1c367cc59eab6f950296",
        correctAnswer: "Chickpeas ",
        incorrectAnswers: ["Lentils", "Split Yellow Peas", "Adzuki"],
        question: {
          text: "What type of pulses are used in humous?",
        },
        tags: ["food", "food_and_drink"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "food_and_drink",
        id: "622a1c367cc59eab6f950262",
        correctAnswer: "India ",
        incorrectAnswers: ["Jamaica", "France", "The USA"],
        question: {
          text: "Which country does one associate 'Dum Aloo'?",
        },
        tags: ["food_and_drink"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "food_and_drink",
        id: "625007160d86c8f685d80f13",
        correctAnswer: "Small little pies",
        incorrectAnswers: ["Little wheels", "Large reeds", "Bibs"],
        question: {
          text: "The pasta tortellini has what meaning in Italian?",
        },
        tags: ["food", "words", "language", "food_and_drink"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
    ],
  },
  {
    category: "Sports and Leisure",
    description:
      "Get ready to flex your muscles with sports and leisure trivia",
    image: "/images/sports-and-leisure-card.webp",
    smallerImage: "/images/sports-and-leisure-card-sm.webp",
    questions: [
      {
        category: "general_knowledge",
        id: "622a1c357cc59eab6f94fc5d",
        correctAnswer: "Salopettes",
        incorrectAnswers: ["Finifugal", "Futz", "Fudgel"],
        question: {
          text: "Which word is defined as 'high-waisted skiing pants with shoulder straps'?",
        },
        tags: ["words", "fashion", "general_knowledge"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "general_knowledge",
        id: "622a1c3d7cc59eab6f951be3",
        correctAnswer: "LXIX",
        incorrectAnswers: ["CXIX", "LIXX", "CIXX"],
        question: {
          text: "How do you write 69 in Roman numerals?",
        },
        tags: ["numbers", "romans", "general_knowledge"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "general_knowledge",
        id: "622a1c3a7cc59eab6f951043",
        correctAnswer: "Lesser Lion",
        incorrectAnswers: ["Iron Lion", "Ferocious Lion", "Brave Lion"],
        question: {
          text: "What is the meaning of the name of the constellation Leo Minor ?",
        },
        tags: ["astronomy", "names", "general_knowledge"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "general_knowledge",
        id: "622a1c3d7cc59eab6f951c6a",
        correctAnswer: "Little Jack Horner",
        incorrectAnswers: ["Humpty Dumpty", "Jack", "Happy Hungry Harry"],
        question: {
          text: "According to the nursery rhyme, who, 'sat in the corner eating a Christmas Pie''?",
        },
        tags: ["general_knowledge"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "general_knowledge",
        id: "622a1c377cc59eab6f950410",
        correctAnswer: "Ethiopia",
        incorrectAnswers: ["Somalia", "Eritrea", "Uganda"],
        question: {
          text: "The first Live Aid was to benefit which starving country?",
        },
        tags: ["general_knowledge"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "general_knowledge",
        id: "646140774d46e537ca8cd9b7",
        correctAnswer: "Casting",
        incorrectAnswers: ["Fishing", "Baiting", "Trolling"],
        question: {
          text: "What term, which refers to the selection of performers for a film, is also used to describe the process of fishermen catching fish?",
        },
        tags: ["film_and_tv", "words"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "general_knowledge",
        id: "622a1c357cc59eab6f94fc6c",
        correctAnswer: "Macrosmatic",
        incorrectAnswers: ["Nudiustertian", "Conjubilant", "Gubbins"],
        question: {
          text: "Which word is defined as 'having a good sense of smell'?",
        },
        tags: ["words", "general_knowledge"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "general_knowledge",
        id: "622a1c357cc59eab6f94fc82",
        correctAnswer: "Flummox",
        incorrectAnswers: [
          "Argle-bargle",
          "Kakorrhaphiophobia",
          "Pauciloquent",
        ],
        question: {
          text: "Which word is defined as 'to perplex someone greatly'?",
        },
        tags: ["words", "general_knowledge"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "general_knowledge",
        id: "648889175dba6c873ef650d6",
        correctAnswer: "A raconteur",
        incorrectAnswers: ["A troubadour", "A dilettante", "A bard"],
        question: {
          text: "What term for someone who tells stories and anecdotes with skill and wit?",
        },
        tags: ["words", "language"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "general_knowledge",
        id: "648888d35dba6c873ef6507f",
        correctAnswer: "Crosshairs",
        incorrectAnswers: ["Target", "Aiming point", "Scope lines"],
        question: {
          text: "What is the technical name for the pair of intersecting lines in a firearm scope?",
        },
        tags: ["weapons", "words", "military"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
    ],
  },
  {
    category: "General Knowledge",
    description: "Test your wits with a whirlwind of general knowledge trivia",
    image: "/images/general-knowledge-card.webp",
    smallerImage: "/images/general-knowledge-card-sm.webp",
    questions: [
      {
        category: "general_knowledge",
        id: "622a1c357cc59eab6f94fc5d",
        correctAnswer: "Salopettes",
        incorrectAnswers: ["Finifugal", "Futz", "Fudgel"],
        question: {
          text: "Which word is defined as 'high-waisted skiing pants with shoulder straps'?",
        },
        tags: ["words", "fashion", "general_knowledge"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "general_knowledge",
        id: "622a1c3d7cc59eab6f951be3",
        correctAnswer: "LXIX",
        incorrectAnswers: ["CXIX", "LIXX", "CIXX"],
        question: {
          text: "How do you write 69 in Roman numerals?",
        },
        tags: ["numbers", "romans", "general_knowledge"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "general_knowledge",
        id: "622a1c3a7cc59eab6f951043",
        correctAnswer: "Lesser Lion",
        incorrectAnswers: ["Iron Lion", "Ferocious Lion", "Brave Lion"],
        question: {
          text: "What is the meaning of the name of the constellation Leo Minor ?",
        },
        tags: ["astronomy", "names", "general_knowledge"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "general_knowledge",
        id: "622a1c3d7cc59eab6f951c6a",
        correctAnswer: "Little Jack Horner",
        incorrectAnswers: ["Humpty Dumpty", "Jack", "Happy Hungry Harry"],
        question: {
          text: "According to the nursery rhyme, who, 'sat in the corner eating a Christmas Pie''?",
        },
        tags: ["general_knowledge"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "general_knowledge",
        id: "622a1c377cc59eab6f950410",
        correctAnswer: "Ethiopia",
        incorrectAnswers: ["Somalia", "Eritrea", "Uganda"],
        question: {
          text: "The first Live Aid was to benefit which starving country?",
        },
        tags: ["general_knowledge"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "general_knowledge",
        id: "646140774d46e537ca8cd9b7",
        correctAnswer: "Casting",
        incorrectAnswers: ["Fishing", "Baiting", "Trolling"],
        question: {
          text: "What term, which refers to the selection of performers for a film, is also used to describe the process of fishermen catching fish?",
        },
        tags: ["film_and_tv", "words"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "general_knowledge",
        id: "622a1c357cc59eab6f94fc6c",
        correctAnswer: "Macrosmatic",
        incorrectAnswers: ["Nudiustertian", "Conjubilant", "Gubbins"],
        question: {
          text: "Which word is defined as 'having a good sense of smell'?",
        },
        tags: ["words", "general_knowledge"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "general_knowledge",
        id: "622a1c357cc59eab6f94fc82",
        correctAnswer: "Flummox",
        incorrectAnswers: [
          "Argle-bargle",
          "Kakorrhaphiophobia",
          "Pauciloquent",
        ],
        question: {
          text: "Which word is defined as 'to perplex someone greatly'?",
        },
        tags: ["words", "general_knowledge"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "general_knowledge",
        id: "648889175dba6c873ef650d6",
        correctAnswer: "A raconteur",
        incorrectAnswers: ["A troubadour", "A dilettante", "A bard"],
        question: {
          text: "What term for someone who tells stories and anecdotes with skill and wit?",
        },
        tags: ["words", "language"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "general_knowledge",
        id: "648888d35dba6c873ef6507f",
        correctAnswer: "Crosshairs",
        incorrectAnswers: ["Target", "Aiming point", "Scope lines"],
        question: {
          text: "What is the technical name for the pair of intersecting lines in a firearm scope?",
        },
        tags: ["weapons", "words", "military"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
    ],
  },
];

export default preparedQuizzes;
