export const preparedQuizzes = [
  {
    category: "Music",
    text: "History Quiz lorem ipsumasdads",
    image: "https://mui.com/static/images/cards/contemplative-reptile.jpg",
    questions: [
      {
        category: "history",
        id: "65056f0c7a97013de78b53bc",
        correctAnswer: "Russia",
        incorrectAnswers: ["Japan", "France", "Canada"],
        question: {
          text: "Which country was suspended from the G8 in 2014?",
        },
        tags: ["history", "2010's", "organisations", "organizations"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "647edb8d520523194910c347",
        correctAnswer: "1929",
        incorrectAnswers: ["1987", "2001", "2008"],
        question: {
          text: "In what year did the Dow Jones Industrial Average crash and lose 23% of its value in what is known as 'Black Tuesday'?",
        },
        tags: ["economics", "events", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c3c7cc59eab6f951afe",
        correctAnswer: "Salem",
        incorrectAnswers: ["Greensboro", "Alexandria", "Wilmington"],
        question: {
          text: "In which Massachusetts town were 20 people executed for witchcraft in 1692?",
        },
        tags: ["1600's", "usa", "halloween", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c357cc59eab6f94fd41",
        correctAnswer: "Constantine",
        incorrectAnswers: ["Byzantine", "Marcus Aurelius", "Trajan"],
        question: {
          text: "Which Roman Emperor moved the capital from Rome to the city now known as Istanbul? ",
        },
        tags: ["romans", "classics", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c367cc59eab6f950358",
        correctAnswer: "John Adams",
        incorrectAnswers: [
          "Thomas Jefferson",
          "Andrew Jackson",
          "James Monroe",
        ],
        question: {
          text: "Who was George Washington's vice-president? ",
        },
        tags: ["history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
    ],
  },
  {
    category: "Sports and Leisure",
    text: "History Quiz lorem ipsumasdads",
    image: "https://mui.com/static/images/cards/contemplative-reptile.jpg",
    questions: [
      {
        category: "history",
        id: "65056f0c7a97013de78b53bc",
        correctAnswer: "Russia",
        incorrectAnswers: ["Japan", "France", "Canada"],
        question: {
          text: "Which country was suspended from the G8 in 2014? ",
        },
        tags: ["history", "2010's", "organisations", "organizations"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "647edb8d520523194910c347",
        correctAnswer: "1929",
        incorrectAnswers: ["1987", "2001", "2008"],
        question: {
          text: "In what year did the Dow Jones Industrial Average crash and lose 23% of its value in what is known as 'Black Tuesday'?",
        },
        tags: ["economics", "events", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c3c7cc59eab6f951afe",
        correctAnswer: "Salem",
        incorrectAnswers: ["Greensboro", "Alexandria", "Wilmington"],
        question: {
          text: "In which Massachusetts town were 20 people executed for witchcraft in 1692? ",
        },
        tags: ["1600's", "usa", "halloween", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c357cc59eab6f94fd41",
        correctAnswer: "Constantine",
        incorrectAnswers: ["Byzantine", "Marcus Aurelius", "Trajan"],
        question: {
          text: "Which Roman Emperor moved the capital from Rome to the city now known as Istanbul? ",
        },
        tags: ["romans", "classics", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c367cc59eab6f950358",
        correctAnswer: "John Adams",
        incorrectAnswers: [
          "Thomas Jefferson",
          "Andrew Jackson",
          "James Monroe",
        ],
        question: {
          text: "Who was George Washington's vice-president? ",
        },
        tags: ["history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
    ],
  },
  {
    category: "Film and TV",
    text: "History Quiz lorem ipsumasdads",
    image: "https://mui.com/static/images/cards/contemplative-reptile.jpg",
    questions: [
      {
        category: "history",
        id: "65056f0c7a97013de78b53bc",
        correctAnswer: "Russia",
        incorrectAnswers: ["Japan", "France", "Canada"],
        question: {
          text: "Which country was suspended from the G8 in 2014? ",
        },
        tags: ["history", "2010's", "organisations", "organizations"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "647edb8d520523194910c347",
        correctAnswer: "1929",
        incorrectAnswers: ["1987", "2001", "2008"],
        question: {
          text: "In what year did the Dow Jones Industrial Average crash and lose 23% of its value in what is known as 'Black Tuesday'?",
        },
        tags: ["economics", "events", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c3c7cc59eab6f951afe",
        correctAnswer: "Salem",
        incorrectAnswers: ["Greensboro", "Alexandria", "Wilmington"],
        question: {
          text: "In which Massachusetts town were 20 people executed for witchcraft in 1692? ",
        },
        tags: ["1600's", "usa", "halloween", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c357cc59eab6f94fd41",
        correctAnswer: "Constantine",
        incorrectAnswers: ["Byzantine", "Marcus Aurelius", "Trajan"],
        question: {
          text: "Which Roman Emperor moved the capital from Rome to the city now known as Istanbul? ",
        },
        tags: ["romans", "classics", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
    ],
  },
  {
    category: "Arts and Literature",
    text: "History Quiz lorem ipsumasdads",
    image: "https://mui.com/static/images/cards/contemplative-reptile.jpg",
    questions: [
      {
        category: "history",
        id: "65056f0c7a97013de78b53bc",
        correctAnswer: "Russia",
        incorrectAnswers: ["Japan", "France", "Canada"],
        question: {
          text: "Which country was suspended from the G8 in 2014? ",
        },
        tags: ["history", "2010's", "organisations", "organizations"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "647edb8d520523194910c347",
        correctAnswer: "1929",
        incorrectAnswers: ["1987", "2001", "2008"],
        question: {
          text: "In what year did the Dow Jones Industrial Average crash and lose 23% of its value in what is known as 'Black Tuesday'?",
        },
        tags: ["economics", "events", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c3c7cc59eab6f951afe",
        correctAnswer: "Salem",
        incorrectAnswers: ["Greensboro", "Alexandria", "Wilmington"],
        question: {
          text: "In which Massachusetts town were 20 people executed for witchcraft in 1692? ",
        },
        tags: ["1600's", "usa", "halloween", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c357cc59eab6f94fd41",
        correctAnswer: "Constantine",
        incorrectAnswers: ["Byzantine", "Marcus Aurelius", "Trajan"],
        question: {
          text: "Which Roman Emperor moved the capital from Rome to the city now known as Istanbul? ",
        },
        tags: ["romans", "classics", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
    ],
  },
  {
    category: "History",
    text: "History Quiz lorem ipsumasdads",
    image: "https://mui.com/static/images/cards/contemplative-reptile.jpg",
    questions: [
      {
        category: "history",
        id: "65056f0c7a97013de78b53bc",
        correctAnswer: "Russia",
        incorrectAnswers: ["Japan", "France", "Canada"],
        question: {
          text: "Which country was suspended from the G8 in 2014? ",
        },
        tags: ["history", "2010's", "organisations", "organizations"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "647edb8d520523194910c347",
        correctAnswer: "1929",
        incorrectAnswers: ["1987", "2001", "2008"],
        question: {
          text: "In what year did the Dow Jones Industrial Average crash and lose 23% of its value in what is known as 'Black Tuesday'?",
        },
        tags: ["economics", "events", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c3c7cc59eab6f951afe",
        correctAnswer: "Salem",
        incorrectAnswers: ["Greensboro", "Alexandria", "Wilmington"],
        question: {
          text: "In which Massachusetts town were 20 people executed for witchcraft in 1692? ",
        },
        tags: ["1600's", "usa", "halloween", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c357cc59eab6f94fd41",
        correctAnswer: "Constantine",
        incorrectAnswers: ["Byzantine", "Marcus Aurelius", "Trajan"],
        question: {
          text: "Which Roman Emperor moved the capital from Rome to the city now known as Istanbul? ",
        },
        tags: ["romans", "classics", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
    ],
  },
  {
    category: "Society and Culture",
    text: "History Quiz lorem ipsumasdads",
    image: "https://mui.com/static/images/cards/contemplative-reptile.jpg",
    questions: [
      {
        category: "history",
        id: "65056f0c7a97013de78b53bc",
        correctAnswer: "Russia",
        incorrectAnswers: ["Japan", "France", "Canada"],
        question: {
          text: "Which country was suspended from the G8 in 2014? ",
        },
        tags: ["history", "2010's", "organisations", "organizations"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "647edb8d520523194910c347",
        correctAnswer: "1929",
        incorrectAnswers: ["1987", "2001", "2008"],
        question: {
          text: "In what year did the Dow Jones Industrial Average crash and lose 23% of its value in what is known as 'Black Tuesday'?",
        },
        tags: ["economics", "events", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c3c7cc59eab6f951afe",
        correctAnswer: "Salem",
        incorrectAnswers: ["Greensboro", "Alexandria", "Wilmington"],
        question: {
          text: "In which Massachusetts town were 20 people executed for witchcraft in 1692? ",
        },
        tags: ["1600's", "usa", "halloween", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c357cc59eab6f94fd41",
        correctAnswer: "Constantine",
        incorrectAnswers: ["Byzantine", "Marcus Aurelius", "Trajan"],
        question: {
          text: "Which Roman Emperor moved the capital from Rome to the city now known as Istanbul? ",
        },
        tags: ["romans", "classics", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
    ],
  },
  {
    category: "Science",
    text: "History Quiz lorem ipsumasdads",
    image: "https://mui.com/static/images/cards/contemplative-reptile.jpg",
    questions: [
      {
        category: "history",
        id: "65056f0c7a97013de78b53bc",
        correctAnswer: "Russia",
        incorrectAnswers: ["Japan", "France", "Canada"],
        question: {
          text: "Which country was suspended from the G8 in 2014? ",
        },
        tags: ["history", "2010's", "organisations", "organizations"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "647edb8d520523194910c347",
        correctAnswer: "1929",
        incorrectAnswers: ["1987", "2001", "2008"],
        question: {
          text: "In what year did the Dow Jones Industrial Average crash and lose 23% of its value in what is known as 'Black Tuesday'?",
        },
        tags: ["economics", "events", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c3c7cc59eab6f951afe",
        correctAnswer: "Salem",
        incorrectAnswers: ["Greensboro", "Alexandria", "Wilmington"],
        question: {
          text: "In which Massachusetts town were 20 people executed for witchcraft in 1692? ",
        },
        tags: ["1600's", "usa", "halloween", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c357cc59eab6f94fd41",
        correctAnswer: "Constantine",
        incorrectAnswers: ["Byzantine", "Marcus Aurelius", "Trajan"],
        question: {
          text: "Which Roman Emperor moved the capital from Rome to the city now known as Istanbul? ",
        },
        tags: ["romans", "classics", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
    ],
  },
  {
    category: "Geography",
    text: "History Quiz lorem ipsumasdads",
    image: "https://mui.com/static/images/cards/contemplative-reptile.jpg",
    questions: [
      {
        category: "history",
        id: "65056f0c7a97013de78b53bc",
        correctAnswer: "Russia",
        incorrectAnswers: ["Japan", "France", "Canada"],
        question: {
          text: "Which country was suspended from the G8 in 2014? ",
        },
        tags: ["history", "2010's", "organisations", "organizations"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "647edb8d520523194910c347",
        correctAnswer: "1929",
        incorrectAnswers: ["1987", "2001", "2008"],
        question: {
          text: "In what year did the Dow Jones Industrial Average crash and lose 23% of its value in what is known as 'Black Tuesday'?",
        },
        tags: ["economics", "events", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c3c7cc59eab6f951afe",
        correctAnswer: "Salem",
        incorrectAnswers: ["Greensboro", "Alexandria", "Wilmington"],
        question: {
          text: "In which Massachusetts town were 20 people executed for witchcraft in 1692? ",
        },
        tags: ["1600's", "usa", "halloween", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c357cc59eab6f94fd41",
        correctAnswer: "Constantine",
        incorrectAnswers: ["Byzantine", "Marcus Aurelius", "Trajan"],
        question: {
          text: "Which Roman Emperor moved the capital from Rome to the city now known as Istanbul? ",
        },
        tags: ["romans", "classics", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
    ],
  },
  {
    category: "Food and Drink",
    text: "History Quiz lorem ipsumasdads",
    image: "https://mui.com/static/images/cards/contemplative-reptile.jpg",
    questions: [
      {
        category: "history",
        id: "65056f0c7a97013de78b53bc",
        correctAnswer: "Russia",
        incorrectAnswers: ["Japan", "France", "Canada"],
        question: {
          text: "Which country was suspended from the G8 in 2014? ",
        },
        tags: ["history", "2010's", "organisations", "organizations"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "647edb8d520523194910c347",
        correctAnswer: "1929",
        incorrectAnswers: ["1987", "2001", "2008"],
        question: {
          text: "In what year did the Dow Jones Industrial Average crash and lose 23% of its value in what is known as 'Black Tuesday'?",
        },
        tags: ["economics", "events", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c3c7cc59eab6f951afe",
        correctAnswer: "Salem",
        incorrectAnswers: ["Greensboro", "Alexandria", "Wilmington"],
        question: {
          text: "In which Massachusetts town were 20 people executed for witchcraft in 1692? ",
        },
        tags: ["1600's", "usa", "halloween", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c357cc59eab6f94fd41",
        correctAnswer: "Constantine",
        incorrectAnswers: ["Byzantine", "Marcus Aurelius", "Trajan"],
        question: {
          text: "Which Roman Emperor moved the capital from Rome to the city now known as Istanbul? ",
        },
        tags: ["romans", "classics", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
    ],
  },
  {
    category: "General Knowledge",
    text: "History Quiz lorem ipsumasdads",
    image: "https://mui.com/static/images/cards/contemplative-reptile.jpg",
    questions: [
      {
        category: "history",
        id: "65056f0c7a97013de78b53bc",
        correctAnswer: "Russia",
        incorrectAnswers: ["Japan", "France", "Canada"],
        question: {
          text: "Which country was suspended from the G8 in 2014? ",
        },
        tags: ["history", "2010's", "organisations", "organizations"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "647edb8d520523194910c347",
        correctAnswer: "1929",
        incorrectAnswers: ["1987", "2001", "2008"],
        question: {
          text: "In what year did the Dow Jones Industrial Average crash and lose 23% of its value in what is known as 'Black Tuesday'?",
        },
        tags: ["economics", "events", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c3c7cc59eab6f951afe",
        correctAnswer: "Salem",
        incorrectAnswers: ["Greensboro", "Alexandria", "Wilmington"],
        question: {
          text: "In which Massachusetts town were 20 people executed for witchcraft in 1692? ",
        },
        tags: ["1600's", "usa", "halloween", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
      {
        category: "history",
        id: "622a1c357cc59eab6f94fd41",
        correctAnswer: "Constantine",
        incorrectAnswers: ["Byzantine", "Marcus Aurelius", "Trajan"],
        question: {
          text: "Which Roman Emperor moved the capital from Rome to the city now known as Istanbul? ",
        },
        tags: ["romans", "classics", "history"],
        type: "text_choice",
        difficulty: "medium",
        regions: [],
        isNiche: false,
      },
    ],
  },
];
